# -wall: report all the warnings and errors,maybe not.
# -g: 打开调试

CFLAGS=-Wall -g

# 使用make的话，默认会执行all下面的指令，如果没有all：这两行指令，使用make会默认执行clean指令。
# 此外，如果在all：后面加上hello，执行make all后会生成一个hello和一个all。

all:
	gcc hello.c -o all


# use "make clean" will run it

clean:
	    rm -f hello
